// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ptera/v1/ptera.proto

package ptera

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl       string                 `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_ptera_v1_ptera_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_ptera_v1_ptera_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_ptera_v1_ptera_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type Card struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId       string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Grade           int32                  `protobuf:"varint,4,opt,name=grade,proto3" json:"grade,omitempty"`
	Position        string                 `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	AffiliatedGroup *string                `protobuf:"bytes,6,opt,name=affiliated_group,json=affiliatedGroup,proto3,oneof" json:"affiliated_group,omitempty"`
	Hobby           string                 `protobuf:"bytes,7,opt,name=hobby,proto3" json:"hobby,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_ptera_v1_ptera_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_ptera_v1_ptera_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_ptera_v1_ptera_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *Card) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Card) GetAffiliatedGroup() string {
	if x != nil && x.AffiliatedGroup != nil {
		return *x.AffiliatedGroup
	}
	return ""
}

func (x *Card) GetHobby() string {
	if x != nil {
		return x.Hobby
	}
	return ""
}

func (x *Card) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Card) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Card) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_ptera_v1_ptera_proto protoreflect.FileDescriptor

const file_ptera_v1_ptera_proto_rawDesc = "" +
	"\n" +
	"\x14ptera/v1/ptera.proto\x12\bptera.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"j\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x00R\x05email\x88\x01\x01B\b\n" +
	"\x06_email\"\xd0\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05grade\x18\x04 \x01(\x05R\x05grade\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\tR\bposition\x12.\n" +
	"\x10affiliated_group\x18\x06 \x01(\tH\x00R\x0faffiliatedGroup\x88\x01\x01\x12\x14\n" +
	"\x05hobby\x18\a \x01(\tR\x05hobby\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\t \x01(\tR\bimageUrl\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x13\n" +
	"\x11_affiliated_group2\x0e\n" +
	"\fPteraServiceBAZ?github.com/jyogi-web/2025_Ptera/backend/pkg/grpc/ptera/v1;pterab\x06proto3"

var (
	file_ptera_v1_ptera_proto_rawDescOnce sync.Once
	file_ptera_v1_ptera_proto_rawDescData []byte
)

func file_ptera_v1_ptera_proto_rawDescGZIP() []byte {
	file_ptera_v1_ptera_proto_rawDescOnce.Do(func() {
		file_ptera_v1_ptera_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ptera_v1_ptera_proto_rawDesc), len(file_ptera_v1_ptera_proto_rawDesc)))
	})
	return file_ptera_v1_ptera_proto_rawDescData
}

var file_ptera_v1_ptera_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ptera_v1_ptera_proto_goTypes = []any{
	(*User)(nil),                  // 0: ptera.v1.User
	(*Card)(nil),                  // 1: ptera.v1.Card
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_ptera_v1_ptera_proto_depIdxs = []int32{
	2, // 0: ptera.v1.Card.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ptera_v1_ptera_proto_init() }
func file_ptera_v1_ptera_proto_init() {
	if File_ptera_v1_ptera_proto != nil {
		return
	}
	file_ptera_v1_ptera_proto_msgTypes[0].OneofWrappers = []any{}
	file_ptera_v1_ptera_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ptera_v1_ptera_proto_rawDesc), len(file_ptera_v1_ptera_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ptera_v1_ptera_proto_goTypes,
		DependencyIndexes: file_ptera_v1_ptera_proto_depIdxs,
		MessageInfos:      file_ptera_v1_ptera_proto_msgTypes,
	}.Build()
	File_ptera_v1_ptera_proto = out.File
	file_ptera_v1_ptera_proto_goTypes = nil
	file_ptera_v1_ptera_proto_depIdxs = nil
}
