// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ptera/v1/ptera.proto

package ptera

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl       string                 `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_ptera_v1_ptera_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_ptera_v1_ptera_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_ptera_v1_ptera_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Grade         int32                  `protobuf:"varint,4,opt,name=grade,proto3" json:"grade,omitempty"`
	Position      string                 `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Faculty       string                 `protobuf:"bytes,6,opt,name=faculty,proto3" json:"faculty,omitempty"`
	Department    string                 `protobuf:"bytes,7,opt,name=department,proto3" json:"department,omitempty"`
	Hobby         string                 `protobuf:"bytes,8,opt,name=hobby,proto3" json:"hobby,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,10,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_ptera_v1_ptera_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_ptera_v1_ptera_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_ptera_v1_ptera_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *Card) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Card) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

func (x *Card) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Card) GetHobby() string {
	if x != nil {
		return x.Hobby
	}
	return ""
}

func (x *Card) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Card) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Card) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CompleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"` // 画像URL
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`                   // 既存の名前
	Faculty       *string                `protobuf:"bytes,3,opt,name=faculty,proto3,oneof" json:"faculty,omitempty"`             // 既存の学部
	Department    *string                `protobuf:"bytes,4,opt,name=department,proto3,oneof" json:"department,omitempty"`       // 既存の学科
	Grade         *int32                 `protobuf:"varint,5,opt,name=grade,proto3,oneof" json:"grade,omitempty"`                // 既存の学年
	Position      *string                `protobuf:"bytes,6,opt,name=position,proto3,oneof" json:"position,omitempty"`           // 既存の職位
	Hobby         *string                `protobuf:"bytes,7,opt,name=hobby,proto3,oneof" json:"hobby,omitempty"`                 // 既存の趣味
	Description   *string                `protobuf:"bytes,8,opt,name=description,proto3,oneof" json:"description,omitempty"`     // 既存の説明文
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteCardRequest) Reset() {
	*x = CompleteCardRequest{}
	mi := &file_ptera_v1_ptera_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteCardRequest) ProtoMessage() {}

func (x *CompleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ptera_v1_ptera_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteCardRequest.ProtoReflect.Descriptor instead.
func (*CompleteCardRequest) Descriptor() ([]byte, []int) {
	return file_ptera_v1_ptera_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteCardRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CompleteCardRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CompleteCardRequest) GetFaculty() string {
	if x != nil && x.Faculty != nil {
		return *x.Faculty
	}
	return ""
}

func (x *CompleteCardRequest) GetDepartment() string {
	if x != nil && x.Department != nil {
		return *x.Department
	}
	return ""
}

func (x *CompleteCardRequest) GetGrade() int32 {
	if x != nil && x.Grade != nil {
		return *x.Grade
	}
	return 0
}

func (x *CompleteCardRequest) GetPosition() string {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return ""
}

func (x *CompleteCardRequest) GetHobby() string {
	if x != nil && x.Hobby != nil {
		return *x.Hobby
	}
	return ""
}

func (x *CompleteCardRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CompleteCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                           // 補完された名前
	Faculty       string                 `protobuf:"bytes,2,opt,name=faculty,proto3" json:"faculty,omitempty"`                                     // 補完された学部
	Department    string                 `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`                               // 補完された学科
	Grade         int32                  `protobuf:"varint,4,opt,name=grade,proto3" json:"grade,omitempty"`                                        // 補完された学年
	Position      string                 `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`                                   // 補完された職位
	Hobby         string                 `protobuf:"bytes,6,opt,name=hobby,proto3" json:"hobby,omitempty"`                                         // 補完された趣味
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`                             // 補完された説明文
	Success       bool                   `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`                                    // 補完が成功したかどうかを示すフラグ
	ErrorMessage  *string                `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"` // エラーメッセージ（存在する場合）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteCardResponse) Reset() {
	*x = CompleteCardResponse{}
	mi := &file_ptera_v1_ptera_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteCardResponse) ProtoMessage() {}

func (x *CompleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ptera_v1_ptera_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteCardResponse.ProtoReflect.Descriptor instead.
func (*CompleteCardResponse) Descriptor() ([]byte, []int) {
	return file_ptera_v1_ptera_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteCardResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompleteCardResponse) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

func (x *CompleteCardResponse) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CompleteCardResponse) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *CompleteCardResponse) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *CompleteCardResponse) GetHobby() string {
	if x != nil {
		return x.Hobby
	}
	return ""
}

func (x *CompleteCardResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CompleteCardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteCardResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

var File_ptera_v1_ptera_proto protoreflect.FileDescriptor

const file_ptera_v1_ptera_proto_rawDesc = "" +
	"\n" +
	"\x14ptera/v1/ptera.proto\x12\bptera.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"j\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x00R\x05email\x88\x01\x01B\b\n" +
	"\x06_email\"\xc5\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05grade\x18\x04 \x01(\x05R\x05grade\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\tR\bposition\x12\x18\n" +
	"\afaculty\x18\x06 \x01(\tR\afaculty\x12\x1e\n" +
	"\n" +
	"department\x18\a \x01(\tR\n" +
	"department\x12\x14\n" +
	"\x05hobby\x18\b \x01(\tR\x05hobby\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\n" +
	" \x01(\tR\bimageUrl\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe2\x02\n" +
	"\x13CompleteCardRequest\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\afaculty\x18\x03 \x01(\tH\x01R\afaculty\x88\x01\x01\x12#\n" +
	"\n" +
	"department\x18\x04 \x01(\tH\x02R\n" +
	"department\x88\x01\x01\x12\x19\n" +
	"\x05grade\x18\x05 \x01(\x05H\x03R\x05grade\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\x06 \x01(\tH\x04R\bposition\x88\x01\x01\x12\x19\n" +
	"\x05hobby\x18\a \x01(\tH\x05R\x05hobby\x88\x01\x01\x12%\n" +
	"\vdescription\x18\b \x01(\tH\x06R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_facultyB\r\n" +
	"\v_departmentB\b\n" +
	"\x06_gradeB\v\n" +
	"\t_positionB\b\n" +
	"\x06_hobbyB\x0e\n" +
	"\f_description\"\xa4\x02\n" +
	"\x14CompleteCardResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\afaculty\x18\x02 \x01(\tR\afaculty\x12\x1e\n" +
	"\n" +
	"department\x18\x03 \x01(\tR\n" +
	"department\x12\x14\n" +
	"\x05grade\x18\x04 \x01(\x05R\x05grade\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\tR\bposition\x12\x14\n" +
	"\x05hobby\x18\x06 \x01(\tR\x05hobby\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x18\n" +
	"\asuccess\x18\b \x01(\bR\asuccess\x12(\n" +
	"\rerror_message\x18\t \x01(\tH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message2]\n" +
	"\fPteraService\x12M\n" +
	"\fCompleteCard\x12\x1d.ptera.v1.CompleteCardRequest\x1a\x1e.ptera.v1.CompleteCardResponseBAZ?github.com/jyogi-web/2025_Ptera/backend/pkg/grpc/ptera/v1;pterab\x06proto3"

var (
	file_ptera_v1_ptera_proto_rawDescOnce sync.Once
	file_ptera_v1_ptera_proto_rawDescData []byte
)

func file_ptera_v1_ptera_proto_rawDescGZIP() []byte {
	file_ptera_v1_ptera_proto_rawDescOnce.Do(func() {
		file_ptera_v1_ptera_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ptera_v1_ptera_proto_rawDesc), len(file_ptera_v1_ptera_proto_rawDesc)))
	})
	return file_ptera_v1_ptera_proto_rawDescData
}

var file_ptera_v1_ptera_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ptera_v1_ptera_proto_goTypes = []any{
	(*User)(nil),                  // 0: ptera.v1.User
	(*Card)(nil),                  // 1: ptera.v1.Card
	(*CompleteCardRequest)(nil),   // 2: ptera.v1.CompleteCardRequest
	(*CompleteCardResponse)(nil),  // 3: ptera.v1.CompleteCardResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_ptera_v1_ptera_proto_depIdxs = []int32{
	4, // 0: ptera.v1.Card.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: ptera.v1.PteraService.CompleteCard:input_type -> ptera.v1.CompleteCardRequest
	3, // 2: ptera.v1.PteraService.CompleteCard:output_type -> ptera.v1.CompleteCardResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ptera_v1_ptera_proto_init() }
func file_ptera_v1_ptera_proto_init() {
	if File_ptera_v1_ptera_proto != nil {
		return
	}
	file_ptera_v1_ptera_proto_msgTypes[0].OneofWrappers = []any{}
	file_ptera_v1_ptera_proto_msgTypes[2].OneofWrappers = []any{}
	file_ptera_v1_ptera_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ptera_v1_ptera_proto_rawDesc), len(file_ptera_v1_ptera_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ptera_v1_ptera_proto_goTypes,
		DependencyIndexes: file_ptera_v1_ptera_proto_depIdxs,
		MessageInfos:      file_ptera_v1_ptera_proto_msgTypes,
	}.Build()
	File_ptera_v1_ptera_proto = out.File
	file_ptera_v1_ptera_proto_goTypes = nil
	file_ptera_v1_ptera_proto_depIdxs = nil
}
