// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: ptera/v1/ptera.proto

package ptera

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// PteraServiceClient is the client API for PteraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PteraServiceClient interface {
}

type pteraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPteraServiceClient(cc grpc.ClientConnInterface) PteraServiceClient {
	return &pteraServiceClient{cc}
}

// PteraServiceServer is the server API for PteraService service.
// All implementations must embed UnimplementedPteraServiceServer
// for forward compatibility.
type PteraServiceServer interface {
	mustEmbedUnimplementedPteraServiceServer()
}

// UnimplementedPteraServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPteraServiceServer struct{}

func (UnimplementedPteraServiceServer) mustEmbedUnimplementedPteraServiceServer() {}
func (UnimplementedPteraServiceServer) testEmbeddedByValue()                      {}

// UnsafePteraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PteraServiceServer will
// result in compilation errors.
type UnsafePteraServiceServer interface {
	mustEmbedUnimplementedPteraServiceServer()
}

func RegisterPteraServiceServer(s grpc.ServiceRegistrar, srv PteraServiceServer) {
	// If the following call panics, it indicates UnimplementedPteraServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PteraService_ServiceDesc, srv)
}

// PteraService_ServiceDesc is the grpc.ServiceDesc for PteraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PteraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ptera.v1.PteraService",
	HandlerType: (*PteraServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "ptera/v1/ptera.proto",
}
