import type { CSSProperties } from "react";

export const styles: { [key: string]: CSSProperties } = {
  container: {
    position: "fixed", // Break out of layout flow (header/footer)
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0, // Behind header/footer if they overlay, or base layer
    width: "100vw",
    height: "100dvh", // Mobile viewport fix
    overflow: "hidden",
    touchAction: "none", // Disable pull-to-refresh & pinch-zoom
    overscrollBehavior: "none", // Prevent scroll chaining
    fontFamily: '"Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    color: "#fff",
    background: "#111",
  },
  overlay: {
    position: "absolute",
    zIndex: 10,
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    pointerEvents: "none",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "20px",
    boxSizing: "border-box",
    background:
      "linear-gradient(180deg, rgba(0,0,0,0.4) 0%, rgba(0,0,0,0) 50%, rgba(0,0,0,0.4) 100%)",
  },
  controls: {
    pointerEvents: "auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "15px",
    marginTop: "20px",
  },
  controlRow: {
    display: "flex",
    gap: "15px",
    alignItems: "center",
    justifyContent: "center",
  },
  startButton: {
    padding: "15px 40px",
    fontSize: "24px",
    fontWeight: "bold",
    background: "linear-gradient(135deg, #FF0080 0%, #7928CA 100%)",
    color: "white",
    border: "none",
    borderRadius: "30px",
    cursor: "pointer",
    boxShadow: "0 0 20px rgba(121, 40, 202, 0.5)",
    textTransform: "uppercase",
    letterSpacing: "2px",
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  // Secondary buttons like Reset or QR Gen
  secondaryButton: {
    padding: "8px 16px",
    fontSize: "12px",
    background: "rgba(255, 255, 255, 0.1)",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    color: "#ccc",
    borderRadius: "20px",
    cursor: "pointer",
    backdropFilter: "blur(5px)",
    transition: "background 0.2s",
  },
  recordsContainer: {
    pointerEvents: "auto",
    background: "rgba(0, 0, 0, 0.6)",
    backdropFilter: "blur(12px)",
    borderRadius: "16px",
    padding: "20px",
    maxHeight: "40vh",
    overflowY: "auto",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    boxShadow: "0 4px 30px rgba(0, 0, 0, 0.5)",
    marginBottom: "20px",
    width: "100%",
    maxWidth: "400px",
    alignSelf: "center",
  },
  recordsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "15px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
    paddingBottom: "10px",
  },
  historyTitle: {
    margin: 0,
    fontSize: "14px",
    textTransform: "uppercase",
    letterSpacing: "1px",
    color: "#888",
  },
  resetButton: {
    background: "transparent",
    border: "1px solid #ff4444",
    color: "#ff4444",
    padding: "4px 12px",
    borderRadius: "12px",
    cursor: "pointer",
    fontSize: "10px",
  },
  recordItem: {
    display: "flex",
    justifyContent: "space-between",
    padding: "8px 0",
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
    fontFamily: "Monaco, Consolas, monospace",
    fontSize: "14px",
  },
  recordTime: {
    color: "#aaa",
  },
  recordDuration: {
    color: "#00ffcc",
    fontWeight: "bold",
    textShadow: "0 0 5px rgba(0, 255, 204, 0.5)",
  },
  measuringBatch: {
    background: "rgba(255, 0, 0, 0.2)",
    border: "1px solid rgba(255, 0, 0, 0.5)",
    color: "#ffaaaa",
    padding: "10px 20px",
    borderRadius: "8px",
    fontWeight: "bold",
    backdropFilter: "blur(4px)",
    animation: "pulse 2s infinite",
  },
  scannerWrapper: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    zIndex: 1, // Above background, below overlay
  },
  signalText: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    color: "#00dac1", // Cyber Cyan
    fontSize: "12rem",
    fontWeight: "900",
    pointerEvents: "none",
    zIndex: 50,
    textShadow: "0 0 10px #00dac1, 0 0 40px #00dac1, 4px 4px 0px #ff00ff", // Neon glow + Magenta offset (glitch)
    fontFamily: '"Arial Black", sans-serif',
    letterSpacing: "-5px",
    fontStyle: "italic", // Speed feel
  },
};
